// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeScanner.Infrastructure.Data;

#nullable disable

namespace TradeScanner.Infrastructure.Migrations
{
    [DbContext(typeof(TradeScannerDbContext))]
    partial class TradeScannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TradeScanner.Core.Domain.Entities.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyPopup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifySound")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StockSymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("TEXT");

                    b.Property<int>("TriggerCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StockSymbolId");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("TradeScanner.Core.Domain.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableAutoScan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePopupAlerts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSoundAlerts")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxResultsPerScan")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinChangePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinTradeScore")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinVolume")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinVolumeRatio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MomentumWeight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NewsWeight")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TechnicalWeight")
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VolumeWeight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnableAutoScan = false,
                            EnablePopupAlerts = true,
                            EnableSoundAlerts = true,
                            MaxPrice = 500.0m,
                            MaxResultsPerScan = 50,
                            MinChangePercent = 2.0m,
                            MinPrice = 1.0m,
                            MinTradeScore = 60,
                            MinVolume = 500000L,
                            MinVolumeRatio = 1.5m,
                            MomentumWeight = 0.35m,
                            NewsWeight = 0.10m,
                            ScanFrequency = 60,
                            TechnicalWeight = 0.25m,
                            Theme = "Dark",
                            VolumeWeight = 0.30m
                        });
                });

            modelBuilder.Entity("TradeScanner.Core.Domain.Entities.ProviderConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedRequests")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RateLimitPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRequests")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProviderConfigs");
                });

            modelBuilder.Entity("TradeScanner.Core.Domain.Entities.ScanResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AvgVolume")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ChangePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MomentumScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NewsScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalsSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Signals");

                    b.Property<int?>("StockSymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TechnicalScore")
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeScore")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VolumeScore")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedAt");

                    b.HasIndex("StockSymbolId");

                    b.HasIndex("Symbol");

                    b.ToTable("ScanResults");
                });

            modelBuilder.Entity("TradeScanner.Core.Domain.Entities.StockSymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MarketCap")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("StockSymbols");
                });

            modelBuilder.Entity("TradeScanner.Core.Domain.Entities.WatchlistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceTarget")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StockSymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StopLoss")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StockSymbolId");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("WatchlistEntries");
                });

            modelBuilder.Entity("TradeScanner.Core.Domain.Entities.AlertRule", b =>
                {
                    b.HasOne("TradeScanner.Core.Domain.Entities.StockSymbol", "StockSymbol")
                        .WithMany("AlertRules")
                        .HasForeignKey("StockSymbolId");

                    b.Navigation("StockSymbol");
                });

            modelBuilder.Entity("TradeScanner.Core.Domain.Entities.ScanResult", b =>
                {
                    b.HasOne("TradeScanner.Core.Domain.Entities.StockSymbol", "StockSymbol")
                        .WithMany("ScanResults")
                        .HasForeignKey("StockSymbolId");

                    b.Navigation("StockSymbol");
                });

            modelBuilder.Entity("TradeScanner.Core.Domain.Entities.WatchlistEntry", b =>
                {
                    b.HasOne("TradeScanner.Core.Domain.Entities.StockSymbol", "StockSymbol")
                        .WithMany("WatchlistEntries")
                        .HasForeignKey("StockSymbolId");

                    b.Navigation("StockSymbol");
                });

            modelBuilder.Entity("TradeScanner.Core.Domain.Entities.StockSymbol", b =>
                {
                    b.Navigation("AlertRules");

                    b.Navigation("ScanResults");

                    b.Navigation("WatchlistEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
